### ISSUE TITLE
[项目推荐] Excelize: Go 语言 Excel 文档基础库

### ISSUE THREAD

**Issue by xuri** [kon9chunkit/GitHub-Chinese-Top-Charts#105]
项目地址: [https://github.com/360EntSecGroup-Skylar/excelize](https://github.com/360EntSecGroup-Skylar/excelize/blob/master/README_zh.md)
中文文档: [https://xuri.me/excelize/zh-hans](https://xuri.me/excelize/zh-hans/)

分类: Go

介绍：Excelize 是 Go 语言编写的用于操作 Office Excel 文档基础库，基于 ECMA-376，ISO/IEC 29500 国际标准。可以使用它来读取、写入由 Microsoft Excel™ 2007 及以上版本创建的电子表格文档。支持 XLSX / XLSM / XLTM 等多种文档格式，高度兼容带有样式、图片(表)、透视表、切片器等复杂组件的文档，并提供流式读写 API，用于处理包含大规模数据的工作簿。可应用于各类报表平台、云计算、边缘计算等系统。

**Comment by kon9chunkit** [comment]
![image](https://user-images.githubusercontent.com/21018904/85241441-614c1600-b46e-11ea-8e24-eb7cc2048522.png)
项目描述包含中文描述即可收录

**Comment by xuri** [comment]
谢谢，但由于一些原因我没有权限修改项目描述，先关闭此 Issue 了。
