### ISSUE TITLE
排行榜应该多几类

### ISSUE THREAD

**Issue by fangjinuo** [kon9chunkit/GitHub-Chinese-Top-Charts#110]
目前只有各语言中，比较出名的，star大于1000的，这明显是不够的，如果只列出这些，还不如不列呢，自己都能搜到，干嘛还要你这里列出来。

其实有很多开源项目，目前star 并不高，但实际很好用的，这些才是真正需要发掘宣传的

**Comment by kon9chunkit** [comment]
感谢你的建议，我们会考虑做这个优化的。

**Comment by kon9chunkit** [comment]
已优化
