### ISSUE TITLE
如果能利用Github的静态网页做成一个可交换式的就非常棒了

### ISSUE THREAD

**Issue by DingProg** [kon9chunkit/GitHub-Chinese-Top-Charts#111]
- 主要是一直滑动找我关注的比较困难，
- 建议如题

**Comment by DingProg** [comment]
我15.6寸的屏幕，这个markdown，就能看中间一点点，还要来回拖
![image](https://user-images.githubusercontent.com/15081256/84855846-b9ae9c80-b097-11ea-9618-18c9074af458.png)

**Comment by Hatcat123** [comment]
github的前端真的闲得慌
