### ISSUE TITLE
教程类,面试类是不是应该单独分一类

### ISSUE THREAD

**Issue by small-ora** [kon9chunkit/GitHub-Chinese-Top-Charts#115]
感觉榜单排名前几的都是教程,面试经验之类的,是否可以单独开一类别展示比较好.

**Comment by 88250** [comment]
赞同 👍 

教程、面经、电子书、Awesome、资源整理等应该单独列，不应该和可运行的项目列在一起。

**Comment by luoqingcheng** [comment]
赞同。机械化爬取高star项目，没有加以区分出教程类、面经类和资源类，搞这种排行榜有什么意义？

**Comment by diggzhang** [comment]
赞同。可以考虑搞一个分类了。

**Comment by Olvi73** [comment]
赞同，教程类的没必要和资源类混在一起

**Comment by AlphaYu** [comment]
> 赞同 👍
> 
> 教程、面经、电子书、Awesome、资源整理等应该单独列，不应该和可运行的项目列在一起。

赞同，很多把guthub当博客用了。

**Comment by zgl1011** [comment]
唉。。。中国的排行榜都是教程、脚手架

**Comment by small-ora** [comment]
> 唉。。。中国的排行榜都是教程、脚手架

哈哈,国人实在,都想着学技术涨工资,所以面经之类的东西比较多.

**Comment by BWR-forWork** [comment]
> > 唉。。。中国的排行榜都是教程、脚手架
> 
> 哈哈,国人实在,都想着学技术涨工资,所以面经之类的东西比较多.

感觉更大的原因是搞有实际内容的开源项目的基本都按照规范来，写的都是英语自然不会进中文排行了( *^-^)

**Comment by small-ora** [comment]
> > > 唉。。。中国的排行榜都是教程、脚手架
> > 
> > 
> > 哈哈,国人实在,都想着学技术涨工资,所以面经之类的东西比较多.
> 
> 感觉更大的原因是搞有实际内容的开源项目的基本都按照规范来，写的都是英语自然不会进中文排行了( *^-^)

有道理

**Comment by kon9chunkit** [comment]
感谢大家的建议，近期会考虑把资料类的项目分离出榜单。

**Comment by kon9chunkit** [comment]
已优化
