### ISSUE TITLE
可以考虑收录showdoc

### ISSUE THREAD

**Issue by star7th** [kon9chunkit/GitHub-Chinese-Top-Charts#14]
可以考虑收录showdoc https://github.com/star7th/showdoc
项目readme用英文写，其实也有中文文档，且主要用户是中文的多。

**Comment by kon9chunkit** [comment]
@star7th 麻烦在 Description 里面也添加中文说明，就可以收录了

**Comment by star7th** [comment]
readme里有中文文档链接，为何要限定des里一定要中文？

**Comment by kon9chunkit** [comment]
是从用户体验的角度考虑的，这里做的是中文榜，里面收录的项目，希望大家直接在最外层页面就能辨识出中文属性，不必非要进入详情页才发现

**Comment by star7th** [comment]
加了

kon9chunkit <notifications@github.com> 于2019年10月11日周五 下午1:27写道：
