### ISSUE TITLE
建议移除 kataras/iris 项目

### ISSUE THREAD

**Issue by daoleno** [kon9chunkit/GitHub-Chinese-Top-Charts#164]
iris 作者严重违反开源精神，在国外 Go 社区一直被诟病，放在榜单里会误导新人。

详情：https://www.reddit.com/r/golang/comments/b481q7/a_warning_about_githubcomkatarasiris/?utm_source=share&utm_medium=web2x&context=3

**Comment by mustard-mh** [comment]
+1

**Comment by kon9chunkit** [comment]
> iris 作者严重违反开源精神，在国外 Go 社区一直被诟病，放在榜单里会误导新人。
> 
> 详情：https://www.reddit.com/r/golang/comments/b481q7/a_warning_about_githubcomkatarasiris/?utm_source=share&utm_medium=web2x&context=3

感谢你的反馈，我们会在接下来的更新中移除该项目。
