### ISSUE TITLE
为什么一些奇怪的项目也能进榜单？

### ISSUE THREAD

**Issue by CHminggao** [kon9chunkit/GitHub-Chinese-Top-Charts#177]
cirosantilli/china-dictatorship
这项目进榜单实在是想不出理由，这玩意也叫优秀？

**Comment by xwi88** [comment]
> cirosantilli/china-dictatorship
> 这项目进榜单实在是想不出理由，这玩意也叫优秀？

爬虫爬的，按照规则搞得，看看就得了

**Comment by rensuperk** [comment]
start多也是一种能力

**Comment by EP012014** [comment]
反动的剔除掉就好了

**Comment by Yang7521** [comment]
JAViewer 这个也在榜单里，看描述我还以为真的是一个什么驾驶模式什么的app，下载下来一看我傻眼了

**Comment by AbnormalProgrammer** [comment]
因为评判的规则是单一的。

**Comment by kon9chunkit** [comment]
> cirosantilli/china-dictatorship 这项目进榜单实在是想不出理由，这玩意也叫优秀？

感谢你的反馈，我们会重视起内容审核问题，接下来的更新会移除掉该项目。
