### ISSUE TITLE
建议移除Alvin9999/new-pac项目（目前在榜上18位）

### ISSUE THREAD

**Issue by pandaQJY** [kon9chunkit/GitHub-Chinese-Top-Charts#179]
该项目是一个免费的爬墙工具，但是他所提供的工具种包含其所要宣传的反共、反华甚至法轮功这样的内容，严重涉及政治敏感。我认为在github这样的技术社区上不应该有这种项目的存在，更何况这个榜单是“优秀”中文项目，会吸引很多人来借鉴和学习，我们不应该传播这种危害祖国安全，损害祖国利益的项目。希望您可以尽快将这个将这个项目从榜单中移除！

**Comment by pandaQJY** [comment]
不要在github上面引入政治斗争，请您一定要认真审查这一份榜单

**Comment by rensuperk** [comment]
支持，虽然轮子很反智，但是依然有很多人无法分辨

**Comment by blogwy** [comment]
排行榜不就是看star数量，我觉得不应该以项目内容来排除任何一个项目。它有那么多star说明确实对大家有帮助。

**Comment by kon9chunkit** [comment]
> 

感谢你的建议，我们会重视起内容审核问题，接下来的更新会移除该项目。

**Comment by kon9chunkit** [comment]
> 该项目是一个免费的爬墙工具，但是他所提供的工具种包含其所要宣传的反共、反华甚至法轮功这样的内容，严重涉及政治敏感。我认为在github这样的技术社区上不应该有这种项目的存在，更何况这个榜单是“优秀”中文项目，会吸引很多人来借鉴和学习，我们不应该传播这种危害祖国安全，损害祖国利益的项目。希望您可以尽快将这个将这个项目从榜单中移除！

感谢你的建议，我们会重视起内容审核问题，接下来的更新会移除该项目。
