### ISSUE TITLE
2K 的py项目，请收纳~

### ISSUE THREAD

**Issue by YongHaoWu** [kon9chunkit/GitHub-Chinese-Top-Charts#2]
https://github.com/YongHaoWu/NeteaseCloudMusicFlac

**Comment by kon9chunkit** [comment]
这个项目本来已经在py榜单里面的，#69

**Comment by kon9chunkit** [comment]
> https://github.com/YongHaoWu/NeteaseCloudMusicFlac

这个项目本来已经在py榜单里面的，#69

**Comment by YongHaoWu** [comment]
牛逼
