### ISSUE TITLE
请求移除总结/归纳/复制/列表等，和本项目同一类型的项目

### ISSUE THREAD

**Issue by abrahamgreyson** [kon9chunkit/GitHub-Chinese-Top-Charts#20]
毫无疑问， 中文 github 里最令人狂热的， 就是那种某一语言、框架、生态的总结、学习类的内容。这类内容通常都不是原创， 大家都喜欢 star，却没几个人看，真是毫无营养，浪费时间。

真心的，如果做，并且打着 top 的名义。 那么只放硬核代码项目吧。只放真正的”项目“。

**Comment by kon9chunkit** [comment]
感谢你的建议，近期会把资料类的项目分离出榜单。
