### ISSUE TITLE
新增 vim script 语言榜单

### ISSUE THREAD

**Issue by wsdjeg** [kon9chunkit/GitHub-Chinese-Top-Charts#23]
感谢分享此项目，建议新增 vim script 语言榜单，这样一些优秀的国人写的 vim 脚本插件也可以收录，同时，也推荐自己的项目 spacevim，目前12000+ star

https://github.com/SpaceVim/SpaceVim

**Comment by mrytsr** [comment]
bilibili/vim-vide: Lightest vimrc, while strong enough. 最轻的vim配置，却足够强！
https://github.com/bilibili/vim-vide

**Comment by kon9chunkit** [comment]
@wsdjeg 增加了Vim script榜单，项目的 Description 可否增加中文描述

**Comment by wsdjeg** [comment]
@kon9chunkit 不好意思，github 这个不方便加中文描述，SpaceVim 中英文是分别有自己的网站和git仓库，中文的仓库是 https://gitee.com/spacevim/SpaceVim
