### ISSUE TITLE
建议移除lantern

### ISSUE THREAD

**Issue by imba-tjd** [kon9chunkit/GitHub-Chinese-Top-Charts#27]
1. 敏感
2. 开发者并不是国人
3. 骗了很多小白的钱
4. 并没有积极开发

**Comment by loadream** [comment]
最主要的是经常连不上

**Comment by hsyh2008** [comment]
关键 没有售后

**Comment by toyue** [comment]
买的话还是诺顿，蓝灯可以做个免费的备用工具，白嫖我推荐VPN gate

**Comment by kon9chunkit** [comment]
> 1. 敏感
> 2. 开发者并不是国人
> 3. 骗了很多小白的钱
> 4. 并没有积极开发

感谢你的建议，接下来的更新会移除该项目。
