### ISSUE TITLE
LaravelS 基于Swoole加速你的Laravel应用

### ISSUE THREAD

**Issue by hhxsv5** [kon9chunkit/GitHub-Chinese-Top-Charts#31]
[LaravelS](https://github.com/hhxsv5/laravel-s)是一个胶水项目，用于快速集成Swoole到Laravel或Lumen，然后赋予它们更好的性能、更多可能性。

**Comment by kon9chunkit** [comment]
@hhxsv5 项目的 Description 也要含有中文说明才可以收录的

**Comment by hhxsv5** [comment]
@kon9chunkit 该项目提供了双语文档，可以参考[中文文档](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md)。

**Comment by kon9chunkit** [comment]
中文总榜 > 软件类 > PHP > 20
