### ISSUE TITLE
请问这是爬虫爬的还是手工维护的？

### ISSUE THREAD

**Issue by esrrhs** [kon9chunkit/GitHub-Chinese-Top-Charts#43]
我的几个项目star也不少，都是中文项目，为何没被收录呀？
求收录
https://github.com/esrrhs/fake
https://github.com/esrrhs/majiang_algorithm
https://github.com/esrrhs/pingtunnel

**Comment by Lizhooh** [comment]
写的太渣

**Comment by esrrhs** [comment]
@Lizhooh 6啊

**Comment by kon9chunkit** [comment]
> 我的几个项目star也不少，都是中文项目，为何没被收录呀？
> 求收录
> https://github.com/esrrhs/fake
> https://github.com/esrrhs/majiang_algorithm
> https://github.com/esrrhs/pingtunnel

第一个在C++榜，第三个在Go榜，第二个上不了Java榜
