### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by OXOYO** [kon9chunkit/GitHub-Chinese-Top-Charts#47]
1.可以做成多个MD，并使用vuePress等文档工具展现;
2.数据可以存在JSON里，通过脚本转成MD，可以做成周刊、图表、OpenAPI等等。

[F2E-Tutorial-Collect](https://github.com/OXOYO/F2E-Tutorial-Collect)是我之前做的通过脚本将我的Chrome书签转成MD文件，并在GitHub Page上展现。

感谢收录了两个我的项目，其实还有几个也可以收录下，手动滑稽。

**Comment by kon9chunkit** [comment]
感谢建议
