### ISSUE TITLE
Vim 插件国内也有好多，可以收集下

### ISSUE THREAD

**Issue by hanxi** [kon9chunkit/GitHub-Chinese-Top-Charts#5]
比如 [Yggdroot/LeaderF](https://github.com/Yggdroot/LeaderF)

**Comment by kon9chunkit** [comment]
这里只收录中文项目哈

**Comment by mrytsr** [comment]
bilibili/vim-vide: Lightest vimrc, while strong enough. 最轻的vim配置，却足够强！
https://github.com/bilibili/vim-vide

**Comment by mrytsr** [comment]
> 这里只收录中文项目哈

bilibili/vim-vide: Lightest vimrc, while strong enough. 最轻的vim配置，却足够强！
https://github.com/bilibili/vim-vide

**Comment by kon9chunkit** [comment]
增加了Vim script榜单
