### ISSUE TITLE
3.3k的Android项目——Auto.js，希望收录

### ISSUE THREAD

**Issue by hyb1996** [kon9chunkit/GitHub-Chinese-Top-Charts#6]
https://github.com/hyb1996/Auto.js

**Comment by kon9chunkit** [comment]
收录有一个小小的基本要求，项目描述、文档正文都要有中文说明，调整一下，下波更新就能收录了

**Comment by hyb1996** [comment]
Auto.js
Android平台上的JavaScript IDE，以自动化为目标提供大量API，方便快捷地编写小应用、工具。

官方文档：https://hyb1996.github.io/AutoJs-Docs/#/

**Comment by kon9chunkit** [comment]
不好意思，可能我表达的不是很清晰，要有中文说明的具体地方是指：GitHub项目的description以及README.md

**Comment by hyb1996** [comment]
@kon9chunkit README之前有啦，项目描述已加入中文

**Comment by kon9chunkit** [comment]
OK，明天更新就会收录了

**Comment by tianly123** [comment]
居然看到我喜欢的big佬

**Comment by licoba** [comment]
活捉：），用auto.js写过蚂蚁森林的投能量脚本

**Comment by kon9chunkit** [comment]
@hyb1996 榜单已更新，你的项目已收录，Java榜#102

**Comment by hyb1996** [comment]
感谢
