### ISSUE TITLE
有json数据么，我可以帮忙写下小程序

### ISSUE THREAD

**Issue by it5200** [kon9chunkit/GitHub-Chinese-Top-Charts#60]
rt

**Comment by WeChatTest001** [comment]
如果你有这个想法，我觉得可以考虑你自己fork添加再pr，同事建议如果有想法可以考虑清洗一遍数据，有些项目建议移除或降低权重。

[**提交自 GitHub Top 小程序**](https://github.com/renyuzhuo/GitHub-Top)
