### ISSUE TITLE
别把纯资料类的项目加进去啊，简直污染这个榜的价值

### ISSUE THREAD

**Issue by ladyrank** [kon9chunkit/GitHub-Chinese-Top-Charts#66]
别把纯资料类的项目加进去啊，简直污染这个榜的价值。

应该只加纯技术类得

**Comment by ryuzheng** [comment]
去掉纯资料类的项目，另立一个资料类的榜单，让他们自己打起来吧

**Comment by vincentlauvlwj** [comment]
赞同

以及学习类、demo 类、awesome list 类。。。

然而偏偏是这些最容易得 star

**Comment by kon9chunkit** [comment]
感谢大家建议，近期会把资料类项目分离出榜单。
