### ISSUE TITLE
【自荐项目】KubeOperator - K8s 集群规划、部署和运营平台

### ISSUE THREAD

**Issue by KubeOperator** [kon9chunkit/GitHub-Chinese-Top-Charts#69]
项目地址：https://github.com/KubeOperator/KubeOperator

类别：Python

项目描述：

KubeOperator 是一个开源项目，通过 Web UI 在 VMware、OpenStack 和物理机上规划、部署和运营生产级别的 Kubernetes 集群。

推荐理由：

提供可视化 UI
支持内网离线环境
支持 GPU
内置应用商店
已通过 CNCF 的 Kubernetes 软件一致性认证。

截图：

![image](https://user-images.githubusercontent.com/52770786/72582148-c9755980-391c-11ea-9b0b-080889bc9c54.png)

**Comment by kon9chunkit** [comment]
已收录于Python榜

**Comment by KubeOperator** [comment]
谢谢。
