### ISSUE TITLE
Go 网络库项目，希望收录

### ISSUE THREAD

**Issue by Allenxuxu** [kon9chunkit/GitHub-Chinese-Top-Charts#7]
https://github.com/Allenxuxu/gev

**Comment by kon9chunkit** [comment]
收录有一个小小的基本要求，项目的description和README.md都要有中文说明，调整后下次更新就收录到了

**Comment by Allenxuxu** [comment]
已经按要求更新 ，感谢收录。

**Comment by kon9chunkit** [comment]
榜单已经更新，你的项目已经收录，Go榜#95
