### ISSUE TITLE
【项目自荐】分布式爬虫管理平台 Crawlab

### ISSUE THREAD

**Issue by tikazyq** [kon9chunkit/GitHub-Chinese-Top-Charts#78]
Star数: ~5k
项目地址: https://github.com/crawlab-team/crawlab
项目描述: 基于Golang的分布式爬虫管理平台，支持Python、NodeJS、Go、Java、PHP等多种编程语言以及多种爬虫框架。

**Comment by salmalik64** [comment]
Ni hao. Nice code

**Comment by salmalik64** [comment]
Keep it up

**Comment by salmalik64** [comment]
Stay home and stay safe

**Comment by kon9chunkit** [comment]
> Star数: ~5k
> 项目地址: https://github.com/crawlab-team/crawlab
> 项目描述: 基于Golang的分布式爬虫管理平台，支持Python、NodeJS、Go、Java、PHP等多种编程语言以及多种爬虫框架。

项目description加上中文描述即可收录

**Comment by tikazyq** [comment]
> > Star数: ~5k
> > 项目地址: https://github.com/crawlab-team/crawlab
> > 项目描述: 基于Golang的分布式爬虫管理平台，支持Python、NodeJS、Go、Java、PHP等多种编程语言以及多种爬虫框架。
> 
> 项目description加上中文描述即可收录

已经加了中文了，请收录，谢谢

**Comment by kon9chunkit** [comment]
> > > Star数: ~5k
> > > 项目地址: https://github.com/crawlab-team/crawlab
> > > 项目描述: 基于Golang的分布式爬虫管理平台，支持Python、NodeJS、Go、Java、PHP等多种编程语言以及多种爬虫框架。
> > 
> > 
> > 项目description加上中文描述即可收录
> 
> 已经加了中文了，请收录，谢谢

已收录于Go榜
