### ISSUE TITLE
为什么有纯日文项目在里面？ --  “TRETJapanNFCReader”

### ISSUE THREAD

**Issue by U97F3** [kon9chunkit/GitHub-Chinese-Top-Charts#79]
想搜搜看有没有NFC相关的项目，结果发现了这个纯日文的项目，麻烦剔除下，有违“项目的 Description 和 README.md 都要包含中文说明”的原则

**Comment by kon9chunkit** [comment]
> 想搜搜看有没有NFC相关的项目，结果发现了这个纯日文的项目，麻烦剔除下，有违“项目的 Description 和 README.md 都要包含中文说明”的原则

已清除日文项目，感谢反馈
