### ISSUE TITLE
希望针对非技术类的项目分类，能增加人工校正的功能

### ISSUE THREAD

**Issue by qianguyihao** [kon9chunkit/GitHub-Chinese-Top-Charts#85]
有些项目只是纯文档、非技术类项目，这些项目，和编程语言的学习没有任何关系，能否人工校正一下，单独做一个分类？

比如下面这个项目，显然就不是JS项目：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way

**Comment by kon9chunkit** [comment]
> 有些项目只是纯文档、非技术类项目，这些项目，和编程语言的学习没有任何关系，能否人工校正一下，单独做一个分类？
> 
> 比如下面这个项目，显然就不是JS项目：
> 
> https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way

感谢你的建议，我们近期会做这个优化。
