### ISSUE TITLE
[项目自荐] AkShare 开源金融数据接口库, 超 20 万下载量, GitHub 1100 Star #1072

### ISSUE THREAD

**Issue by jindaxiang** [kon9chunkit/GitHub-Chinese-Top-Charts#88]
## 项目推荐
- 项目地址：https://github.com/jindaxiang/akshare; docs: https://akshare.readthedocs.io/

- 类别：Python

- 项目后续更新计划：增加更多数据接口，目前本项目已经更新 0.4.56，每日都在维护

- 项目描述：
  - 必写：AkShare 是基于 Python 的开源金融数据接口库, 目的是实现对股票, 期货, 期权, 基金, 外汇, 债券, 指数, 数字货币等金融产品的基本面数据、实时和历史行情数据、衍生数据从数据采集, 数据清洗, 到数据落地的一套开源工具, 满足金融数据科学家, 数据科学爱好者在金融数据获取方面的需求.
  - 可选：可以便利解决数据获取问题，方便金融量化从业人员、科研人员。

- 推荐理由：开源项目; 利用一行代码获取数据，整合各大公开金融数据源。目前本项目已经收获 1100 + star，下载量超过 20 万，微信公众号粉丝超过 1800 人，撰写超 100,000 字的文档；每个数据接口都有丰富的Python示例代码支持。

- 示例代码：
```
import akshare as ak
bond_df = ak.get_country_bond(country="中国", index_name="中国1年期国债", start_date='2000/01/01', end_date='2019/10/17')
print(bond_df)
```

- 截图：
![image](https://user-images.githubusercontent.com/18234520/74135886-0f75c280-4c28-11ea-94be-6ec3d917384d.png)

**Comment by kon9chunkit** [comment]
项目description加上中文描述即可收录

**Comment by jindaxiang** [comment]
> 项目description加上中文描述即可收录

已经更新中文描述，感谢提示

**Comment by kon9chunkit** [comment]
> > 项目description加上中文描述即可收录
> 
> 已经更新中文描述，感谢提示

已收录于Python榜

**Comment by jindaxiang** [comment]
> > > 项目description加上中文描述即可收录
> > 
> > 
> > 已经更新中文描述，感谢提示
> 
> 已收录于Python榜

您好，最近怎么没查到项目在榜上了？

**Comment by FWangZil** [comment]
> > > > 项目description加上中文描述即可收录
> > > 
> > > 
> > > 已经更新中文描述，感谢提示
> > 
> > 
> > 已收录于Python榜
> 
> 您好，最近怎么没查到项目在榜上了？

还真是，我也发现不见了。
