### ISSUE TITLE
项目很不错，再推荐一个Java教程类项目-JavaGuide

### ISSUE THREAD

**Issue by javaguide-tech** [kon9chunkit/GitHub-Chinese-Top-Charts#95]
地址：https://github.com/Snailclimb/JavaGuide
推荐理由：对于初学Java或者准备Java面试的人来说的帮助很大！

最后感谢大佬的整理，收货很大！

**Comment by kon9chunkit** [comment]
> 地址：https://github.com/Snailclimb/JavaGuide
> 推荐理由：对于初学Java或者准备Java面试的人来说的帮助很大！
> 
> 最后感谢大佬的整理，收货很大！

已收录的
